// <auto-generated />
namespace PlusAndComment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class DDD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DDD));
        
        string IMigrationMetadata.Id
        {
            get { return "201707311908350_DDD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
